### ISSUE TITLE
capture_rsync command line option problems

### ISSUE THREAD

**Issue by fmadio** [fmadio/fmadio_scripts#2]
1. --splitmode
   NG pattern;
   [admins@localhost ~]$ ./capture_rsync.py  rsync_001_20160915_0953 --host 192.168.2.95 --user fmadio --pass 100g --spl
   itmode split_100MB --output /home/admins/rsync/ --follow
   RSync Capture Named [rsync_001_20160915_0953]
   RSync Capture Named [split_100MB]
   Follow Mode
   Failed to find capture [split_100MB]

OK pattern;
[admins@localhost ~]$ ./capture_rsync.py  rsync_001_20160915_0953 --host 192.168.2.95 --user fmadio --pass 100g --split split_100MB --output /home/admins/rsync/ --follow
RSync Capture Named [rsync_001_20160915_0953]
Follow Mode
[/home/admins/rsync/rsync_001_20160915_0953_split_100MB/rsync_001_20160915_0953__20160915_09:53:58.325.824.768.pcap] Downloading...   0.100 GB  10.875 sec    0.073860 Gbps
[/home/admins/rsync/rsync_001_20160915_0953_split_100MB/rsync_001_20160915_0953__20160915_09:53:58.406.454.272.pcap] Downloading...   0.100 GB   8.545 sec    0.093748 Gbps
[/home/admins/rsync/rsync_001_20160915_0953_split_100MB/rsync_001_20160915_0953__20160915_09:53:58.486.775.296.pcap] Downloading...^C
Traceback (most recent call last):
  File "./capture_rsync.py", line 667, in <module>
    URLArg)
  File "./capture_rsync.py", line 258, in StreamRSync
    CURLCmd(URL, ' > "' + FileName + '"')
  File "./capture_rsync.py", line 123, in CURLCmd
    List        = commands.getstatusoutput(Cmd)
  File "/usr/lib64/python2.7/commands.py", line 60, in getstatusoutput
    text = pipe.read()
KeyboardInterrupt
1. --filter
   Only NG pattern;
   [admins@localhost ~]$ ./capture_rsync.py  rsync_001_20160915_0953 --host 192.168.2.95 --user fmadio --pass 100g --filter FilterUDP=true --output /home/admins/rsync/ --follow
   RSync Capture Named [rsync_001_20160915_0953]
   Follow Mode
   Traceback (most recent call last):
   File "./capture_rsync.py", line 713, in <module>
     StreamFetch(NewList, OutputDir + "/" + Entry["Name"] + "_", FilterArg, Suffix)
   File "./capture_rsync.py", line 272, in StreamFetch
     FileName =  Prefix + '_' + Split["Time"] + Suffix
   TypeError: list indices must be integers, not str

**Comment by fmadio** [comment]
splitmode cmdline arg fixed fmadio/fmadio_scripts@8b22fe5

**Comment by fmadio** [comment]
followmode + filter bugfix fmadio/fmadio_scripts@c7a367e

**Comment by fmadio** [comment]
regressions updated to include follow mode fmadio/fmadio20_regression@4795269a4c354afa8c971215dd26a22420b350cf

still missing follow + uri filter regression
